apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    project: kubernetes-project
  name: kubernetes-pod
spec:
  containers:
  - image: cyrillendia/mywebapp:latest
    name: kubernetes-pod
    ports:
    - containerPort: 31111
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
