version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "flask-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b340ll2jgl1u"
s3_prefix = "flask-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
