# These values' name are same as the values in the dependency (postgres)' values.yml file
# We use them here to alter the values of the dependency
postgresql:
  fullnameOverride: "postgres"
  image:
    tag: 11.14.0-debian-10-r17
  postgresqlDatabase: elearning3_development
  postgresqlUsername: postgres
  postgresqlPassword: postgrespassword
  databasePort: 5432
#------------------------

configmap: 
  name: postgres-configmap

app:
  project: helm-project
  tier: application

service:
  type: NodePort
  port: 31111
  nodePort: 31111
  targetPort: 3000

image:
  repository: cyrillendia/myhelmwebapp
  tag: latest

deployments:
  name: app
  containerPort: 3000
  imagePullPolicy: Always

initContainers:
  name: check-db-ready
  image: postgres:9.6.5
  command: ['sh', '-c', 
          'until pg_isready -h postgres -p 5432; 
          do echo waiting for database; sleep 5; done;']
