# Write your code here
apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  type: ClusterIP
  selector:
    project: kubernetes-project
    app: database
    tier: backend
  ports:
  - name: database
    port: 5432
    protocol: TCP
